<script lang="ts">
	import { onDestroy, onMount } from 'svelte';

	export let height = '137';

	let interval: undefined | NodeJS.Timeout | number = undefined;
	let isActive = false;

	onMount(() => {
		isActive = true;
		interval = setInterval(() => {
			isActive = !isActive;
		}, 1500);
	});

	onDestroy(() => {
		clearInterval(interval);
	});
</script>

<svg
	width="204"
	{height}
	class:active={isActive}
	viewBox="0 0 204 137"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
>
	<path
		d="M12.0693 12.0693C23.7832 0.355352 41.0249 -2.46398 55.3999 3.61415C54.6661 8.99605 56.3677 14.6484 60.5061 18.7868C64.7408 23.0214 70.5606 24.7046 76.054 23.8378C82.5612 38.3614 79.8525 56.0089 67.9307 67.9307C52.505 83.3564 27.495 83.3564 12.0693 67.9307C-3.35643 52.505 -3.35643 27.495 12.0693 12.0693ZM54.4957 54.4957C62.5014 46.4899 62.5014 33.5101 54.4957 25.5043C46.4899 17.4986 33.5101 17.4986 25.5043 25.5043C17.4986 33.5101 17.4986 46.4899 25.5043 54.4957C33.5101 62.5014 46.4899 62.5014 54.4957 54.4957Z"
		stroke="#0082C9"
		class="svg-elem-1"
	/>
	<path
		d="M45.0693 69.0693C56.7832 57.3554 74.0249 54.536 88.3999 60.6141C87.6661 65.996 89.3677 71.6484 93.5061 75.7868C97.7408 80.0214 103.561 81.7046 109.054 80.8378C115.561 95.3614 112.853 113.009 100.931 124.931C85.505 140.356 60.495 140.356 45.0693 124.931C29.6436 109.505 29.6436 84.495 45.0693 69.0693ZM87.4957 111.496C95.5014 103.49 95.5014 90.5101 87.4957 82.5043C79.4899 74.4986 66.5101 74.4986 58.5043 82.5043C50.4986 90.5101 50.4986 103.49 58.5043 111.496C66.5101 119.501 79.4899 119.501 87.4957 111.496Z"
		stroke="#00A850"
		class="svg-elem-2"
	/>
	<path
		d="M141.5 40C141.5 61.8152 123.815 79.5 102 79.5C80.1848 79.5 62.5 61.8152 62.5 40C62.5 18.1848 80.1848 0.5 102 0.5C123.815 0.5 141.5 18.1848 141.5 40ZM102 60.5C113.322 60.5 122.5 51.3218 122.5 40C122.5 28.6782 113.322 19.5 102 19.5C90.6782 19.5 81.5 28.6782 81.5 40C81.5 51.3218 90.6782 60.5 102 60.5Z"
		stroke="black"
		class="svg-elem-3"
	/>
	<path
		d="M174.5 97C174.5 118.815 156.815 136.5 135 136.5C113.185 136.5 95.5 118.815 95.5 97C95.5 75.1848 113.185 57.5 135 57.5C156.815 57.5 174.5 75.1848 174.5 97ZM135 117.5C146.322 117.5 155.5 108.322 155.5 97C155.5 85.6782 146.322 76.5 135 76.5C123.678 76.5 114.5 85.6782 114.5 97C114.5 108.322 123.678 117.5 135 117.5Z"
		stroke="#FCB32D"
		class="svg-elem-4"
	/>
	<path
		d="M147.838 3.94603C157.84 -0.535219 169.325 -0.645908 179.4 3.61415C178.666 8.99605 180.368 14.6484 184.506 18.7868C188.741 23.0215 194.561 24.7046 200.054 23.8379C206.561 38.3615 203.853 56.0089 191.931 67.9307C176.505 83.3564 151.495 83.3564 136.069 67.9307C124.355 56.2168 121.536 38.9751 127.614 24.6002C132.996 25.3339 138.648 23.6323 142.787 19.4939C147.021 15.2592 148.705 9.43937 147.838 3.94603ZM178.496 54.4957C186.501 46.4899 186.501 33.5101 178.496 25.5043C170.49 17.4986 157.51 17.4986 149.504 25.5043C141.499 33.5101 141.499 46.4899 149.504 54.4957C157.51 62.5014 170.49 62.5014 178.496 54.4957Z"
		stroke="#EF304D"
		class="svg-elem-5"
	/>
</svg>

<style>
	/***************************************************
 * Generated by SVG Artista on 12/7/2023, 8:43:05 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

	svg .svg-elem-1 {
		stroke-dashoffset: 383.0158386230469px;
		stroke-dasharray: 383.0158386230469px;
		-webkit-transition: stroke-dashoffset 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 0s;
		transition: stroke-dashoffset 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 0s;
	}

	svg.active .svg-elem-1 {
		stroke-dashoffset: 0;
	}

	svg .svg-elem-2 {
		stroke-dashoffset: 383.016357421875px;
		stroke-dasharray: 383.016357421875px;
		-webkit-transition: stroke-dashoffset 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 0.12s;
		transition: stroke-dashoffset 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 0.12s;
	}

	svg.active .svg-elem-2 {
		stroke-dashoffset: 0;
	}

	svg .svg-elem-3 {
		stroke-dashoffset: 379.04412841796875px;
		stroke-dasharray: 379.04412841796875px;
		-webkit-transition: stroke-dashoffset 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 0.24s;
		transition: stroke-dashoffset 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 0.24s;
	}

	svg.active .svg-elem-3 {
		stroke-dashoffset: 0;
	}

	svg .svg-elem-4 {
		stroke-dashoffset: 379.04437255859375px;
		stroke-dasharray: 379.04437255859375px;
		-webkit-transition: stroke-dashoffset 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 0.36s;
		transition: stroke-dashoffset 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 0.36s;
	}

	svg.active .svg-elem-4 {
		stroke-dashoffset: 0;
	}

	svg .svg-elem-5 {
		stroke-dashoffset: 386.9884338378906px;
		stroke-dasharray: 386.9884338378906px;
		-webkit-transition: stroke-dashoffset 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 0.48s;
		transition: stroke-dashoffset 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 0.48s;
	}

	svg.active .svg-elem-5 {
		stroke-dashoffset: 0;
	}
</style>
